# Server Configuration
server.port=${PORT:9000}
spring.application.name=discovery-server

# Eureka Server Configuration
# Standalone Eureka Server: Do not register with itself and do not fetch registry
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation mode in local/development environment
eureka.server.enable-self-preservation=false